Add readme file
nextcloud/example-files pull request #26
Opened 2022-10-31 07:59 UTC by luka-nextcloud

* resolves: https://github.com/nextcloud/text/issues/3209

2022-10-31 12:04 UTC, juliushaertl approved these changes

2022-10-31 12:05 UTC, juliushaertl commented on Readme.md
> +# Welcome to Nextcloud! :iphone: :cloud: :computer:
We should insert the actual emoji characters here as text does not support the `:` syntax when opening

2022-10-31 12:05 UTC, juliushaertl requested changes
Small comment

2022-11-02 07:25 UTC, juliushaertl commented on Readme.md
> +# Welcome to Nextcloud! � ☁️ �
```suggestion
# Welcome to Nextcloud! 📱 ☁️ 💻
```

Something seems odd with the encoding here on GitHub

2022-11-07 07:08 UTC, juliushaertl approved these changes

2022-11-07 11:13 UTC, jancborchardt approved these changes

2022-11-07 11:14 UTC, merged